name: 7guis-nextjs
version: 0.0.0
private: true
scripts:
  build: next build
  dev: next dev
  format: prettier --write .
  lint: next lint
  start: next start
dependencies:
  big.js: 6.2.0
  next: 12.1.6
  react: 18.1.0
  react-dom: 18.1.0
devDependencies:
  '@axe-core/react': 4.4.3
  '@picocss/pico': 1.5.3
  '@types/big.js': 6.1.3
  '@types/node': 17.0.42
  '@types/react': 18.0.12
  '@types/react-dom': 18.0.5
  '@typescript-eslint/eslint-plugin': 5.28.0
  '@typescript-eslint/parser': 5.28.0
  eslint: 8.17.0
  eslint-config-next: 12.1.6
  prettier: 2.6.2
  sass: 1.52.3
  typescript: 4.7.3
